// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kraalzibar/v1/core.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationshipUpdate_Operation int32

const (
	RelationshipUpdate_OPERATION_UNSPECIFIED RelationshipUpdate_Operation = 0
	RelationshipUpdate_OPERATION_TOUCH       RelationshipUpdate_Operation = 1
	RelationshipUpdate_OPERATION_DELETE      RelationshipUpdate_Operation = 2
)

// Enum value maps for RelationshipUpdate_Operation.
var (
	RelationshipUpdate_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_TOUCH",
		2: "OPERATION_DELETE",
	}
	RelationshipUpdate_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_TOUCH":       1,
		"OPERATION_DELETE":      2,
	}
)

func (x RelationshipUpdate_Operation) Enum() *RelationshipUpdate_Operation {
	p := new(RelationshipUpdate_Operation)
	*p = x
	return p
}

func (x RelationshipUpdate_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipUpdate_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_kraalzibar_v1_core_proto_enumTypes[0].Descriptor()
}

func (RelationshipUpdate_Operation) Type() protoreflect.EnumType {
	return &file_kraalzibar_v1_core_proto_enumTypes[0]
}

func (x RelationshipUpdate_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipUpdate_Operation.Descriptor instead.
func (RelationshipUpdate_Operation) EnumDescriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{3, 0}
}

type PermissionExpansionTree_IntermediateNode_Operation int32

const (
	PermissionExpansionTree_IntermediateNode_OPERATION_UNSPECIFIED  PermissionExpansionTree_IntermediateNode_Operation = 0
	PermissionExpansionTree_IntermediateNode_OPERATION_UNION        PermissionExpansionTree_IntermediateNode_Operation = 1
	PermissionExpansionTree_IntermediateNode_OPERATION_INTERSECTION PermissionExpansionTree_IntermediateNode_Operation = 2
	PermissionExpansionTree_IntermediateNode_OPERATION_EXCLUSION    PermissionExpansionTree_IntermediateNode_Operation = 3
)

// Enum value maps for PermissionExpansionTree_IntermediateNode_Operation.
var (
	PermissionExpansionTree_IntermediateNode_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_UNION",
		2: "OPERATION_INTERSECTION",
		3: "OPERATION_EXCLUSION",
	}
	PermissionExpansionTree_IntermediateNode_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":  0,
		"OPERATION_UNION":        1,
		"OPERATION_INTERSECTION": 2,
		"OPERATION_EXCLUSION":    3,
	}
)

func (x PermissionExpansionTree_IntermediateNode_Operation) Enum() *PermissionExpansionTree_IntermediateNode_Operation {
	p := new(PermissionExpansionTree_IntermediateNode_Operation)
	*p = x
	return p
}

func (x PermissionExpansionTree_IntermediateNode_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionExpansionTree_IntermediateNode_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_kraalzibar_v1_core_proto_enumTypes[1].Descriptor()
}

func (PermissionExpansionTree_IntermediateNode_Operation) Type() protoreflect.EnumType {
	return &file_kraalzibar_v1_core_proto_enumTypes[1]
}

func (x PermissionExpansionTree_IntermediateNode_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionExpansionTree_IntermediateNode_Operation.Descriptor instead.
func (PermissionExpansionTree_IntermediateNode_Operation) EnumDescriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{7, 1, 0}
}

type ObjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectReference) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectReference) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type SubjectReference struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubjectType     string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectRelation *string                `protobuf:"bytes,3,opt,name=subject_relation,json=subjectRelation,proto3,oneof" json:"subject_relation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubjectReference) Reset() {
	*x = SubjectReference{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectReference) ProtoMessage() {}

func (x *SubjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectReference.ProtoReflect.Descriptor instead.
func (*SubjectReference) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *SubjectReference) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SubjectReference) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectReference) GetSubjectRelation() string {
	if x != nil && x.SubjectRelation != nil {
		return *x.SubjectRelation
	}
	return ""
}

type Relationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectReference       `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *Relationship) GetObject() *ObjectReference {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Relationship) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Relationship) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type RelationshipUpdate struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Operation     RelationshipUpdate_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=kraalzibar.v1.RelationshipUpdate_Operation" json:"operation,omitempty"`
	Relationship  *Relationship                `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipUpdate) Reset() {
	*x = RelationshipUpdate{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipUpdate) ProtoMessage() {}

func (x *RelationshipUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipUpdate.ProtoReflect.Descriptor instead.
func (*RelationshipUpdate) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *RelationshipUpdate) GetOperation() RelationshipUpdate_Operation {
	if x != nil {
		return x.Operation
	}
	return RelationshipUpdate_OPERATION_UNSPECIFIED
}

func (x *RelationshipUpdate) GetRelationship() *Relationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

type ZedToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZedToken) Reset() {
	*x = ZedToken{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZedToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZedToken) ProtoMessage() {}

func (x *ZedToken) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZedToken.ProtoReflect.Descriptor instead.
func (*ZedToken) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *ZedToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Consistency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Requirement:
	//
	//	*Consistency_FullConsistency
	//	*Consistency_MinimizeLatency
	//	*Consistency_AtLeastAsFresh
	//	*Consistency_AtExactSnapshot
	Requirement   isConsistency_Requirement `protobuf_oneof:"requirement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *Consistency) GetRequirement() isConsistency_Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *Consistency) GetFullConsistency() bool {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_FullConsistency); ok {
			return x.FullConsistency
		}
	}
	return false
}

func (x *Consistency) GetMinimizeLatency() bool {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_MinimizeLatency); ok {
			return x.MinimizeLatency
		}
	}
	return false
}

func (x *Consistency) GetAtLeastAsFresh() *ZedToken {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_AtLeastAsFresh); ok {
			return x.AtLeastAsFresh
		}
	}
	return nil
}

func (x *Consistency) GetAtExactSnapshot() *ZedToken {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_AtExactSnapshot); ok {
			return x.AtExactSnapshot
		}
	}
	return nil
}

type isConsistency_Requirement interface {
	isConsistency_Requirement()
}

type Consistency_FullConsistency struct {
	FullConsistency bool `protobuf:"varint,1,opt,name=full_consistency,json=fullConsistency,proto3,oneof"`
}

type Consistency_MinimizeLatency struct {
	MinimizeLatency bool `protobuf:"varint,2,opt,name=minimize_latency,json=minimizeLatency,proto3,oneof"`
}

type Consistency_AtLeastAsFresh struct {
	AtLeastAsFresh *ZedToken `protobuf:"bytes,3,opt,name=at_least_as_fresh,json=atLeastAsFresh,proto3,oneof"`
}

type Consistency_AtExactSnapshot struct {
	AtExactSnapshot *ZedToken `protobuf:"bytes,4,opt,name=at_exact_snapshot,json=atExactSnapshot,proto3,oneof"`
}

func (*Consistency_FullConsistency) isConsistency_Requirement() {}

func (*Consistency_MinimizeLatency) isConsistency_Requirement() {}

func (*Consistency_AtLeastAsFresh) isConsistency_Requirement() {}

func (*Consistency_AtExactSnapshot) isConsistency_Requirement() {}

type RelationshipFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    *string                `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	ObjectId      *string                `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	Relation      *string                `protobuf:"bytes,3,opt,name=relation,proto3,oneof" json:"relation,omitempty"`
	SubjectType   *string                `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3,oneof" json:"subject_type,omitempty"`
	SubjectId     *string                `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3,oneof" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipFilter) Reset() {
	*x = RelationshipFilter{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipFilter) ProtoMessage() {}

func (x *RelationshipFilter) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipFilter.ProtoReflect.Descriptor instead.
func (*RelationshipFilter) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *RelationshipFilter) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

func (x *RelationshipFilter) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *RelationshipFilter) GetRelation() string {
	if x != nil && x.Relation != nil {
		return *x.Relation
	}
	return ""
}

func (x *RelationshipFilter) GetSubjectType() string {
	if x != nil && x.SubjectType != nil {
		return *x.SubjectType
	}
	return ""
}

func (x *RelationshipFilter) GetSubjectId() string {
	if x != nil && x.SubjectId != nil {
		return *x.SubjectId
	}
	return ""
}

type PermissionExpansionTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Node:
	//
	//	*PermissionExpansionTree_Leaf
	//	*PermissionExpansionTree_Intermediate
	Node          isPermissionExpansionTree_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionExpansionTree) Reset() {
	*x = PermissionExpansionTree{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionExpansionTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionExpansionTree) ProtoMessage() {}

func (x *PermissionExpansionTree) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionExpansionTree.ProtoReflect.Descriptor instead.
func (*PermissionExpansionTree) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *PermissionExpansionTree) GetNode() isPermissionExpansionTree_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *PermissionExpansionTree) GetLeaf() *PermissionExpansionTree_LeafNode {
	if x != nil {
		if x, ok := x.Node.(*PermissionExpansionTree_Leaf); ok {
			return x.Leaf
		}
	}
	return nil
}

func (x *PermissionExpansionTree) GetIntermediate() *PermissionExpansionTree_IntermediateNode {
	if x != nil {
		if x, ok := x.Node.(*PermissionExpansionTree_Intermediate); ok {
			return x.Intermediate
		}
	}
	return nil
}

type isPermissionExpansionTree_Node interface {
	isPermissionExpansionTree_Node()
}

type PermissionExpansionTree_Leaf struct {
	Leaf *PermissionExpansionTree_LeafNode `protobuf:"bytes,1,opt,name=leaf,proto3,oneof"`
}

type PermissionExpansionTree_Intermediate struct {
	Intermediate *PermissionExpansionTree_IntermediateNode `protobuf:"bytes,2,opt,name=intermediate,proto3,oneof"`
}

func (*PermissionExpansionTree_Leaf) isPermissionExpansionTree_Node() {}

func (*PermissionExpansionTree_Intermediate) isPermissionExpansionTree_Node() {}

type PermissionExpansionTree_LeafNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *SubjectReference      `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionExpansionTree_LeafNode) Reset() {
	*x = PermissionExpansionTree_LeafNode{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionExpansionTree_LeafNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionExpansionTree_LeafNode) ProtoMessage() {}

func (x *PermissionExpansionTree_LeafNode) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionExpansionTree_LeafNode.ProtoReflect.Descriptor instead.
func (*PermissionExpansionTree_LeafNode) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PermissionExpansionTree_LeafNode) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type PermissionExpansionTree_IntermediateNode struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Operation     PermissionExpansionTree_IntermediateNode_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=kraalzibar.v1.PermissionExpansionTree_IntermediateNode_Operation" json:"operation,omitempty"`
	Children      []*PermissionExpansionTree                         `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionExpansionTree_IntermediateNode) Reset() {
	*x = PermissionExpansionTree_IntermediateNode{}
	mi := &file_kraalzibar_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionExpansionTree_IntermediateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionExpansionTree_IntermediateNode) ProtoMessage() {}

func (x *PermissionExpansionTree_IntermediateNode) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionExpansionTree_IntermediateNode.ProtoReflect.Descriptor instead.
func (*PermissionExpansionTree_IntermediateNode) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_core_proto_rawDescGZIP(), []int{7, 1}
}

func (x *PermissionExpansionTree_IntermediateNode) GetOperation() PermissionExpansionTree_IntermediateNode_Operation {
	if x != nil {
		return x.Operation
	}
	return PermissionExpansionTree_IntermediateNode_OPERATION_UNSPECIFIED
}

func (x *PermissionExpansionTree_IntermediateNode) GetChildren() []*PermissionExpansionTree {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_kraalzibar_v1_core_proto protoreflect.FileDescriptor

const file_kraalzibar_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x18kraalzibar/v1/core.proto\x12\rkraalzibar.v1\"O\n" +
	"\x0fObjectReference\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"\x99\x01\n" +
	"\x10SubjectReference\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x03 \x01(\tH\x00R\x0fsubjectRelation\x88\x01\x01B\x13\n" +
	"\x11_subject_relation\"\x9d\x01\n" +
	"\fRelationship\x126\n" +
	"\x06object\x18\x01 \x01(\v2\x1e.kraalzibar.v1.ObjectReferenceR\x06object\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x129\n" +
	"\asubject\x18\x03 \x01(\v2\x1f.kraalzibar.v1.SubjectReferenceR\asubject\"\xf3\x01\n" +
	"\x12RelationshipUpdate\x12I\n" +
	"\toperation\x18\x01 \x01(\x0e2+.kraalzibar.v1.RelationshipUpdate.OperationR\toperation\x12?\n" +
	"\frelationship\x18\x02 \x01(\v2\x1b.kraalzibar.v1.RelationshipR\frelationship\"Q\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_TOUCH\x10\x01\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x02\" \n" +
	"\bZedToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x83\x02\n" +
	"\vConsistency\x12+\n" +
	"\x10full_consistency\x18\x01 \x01(\bH\x00R\x0ffullConsistency\x12+\n" +
	"\x10minimize_latency\x18\x02 \x01(\bH\x00R\x0fminimizeLatency\x12D\n" +
	"\x11at_least_as_fresh\x18\x03 \x01(\v2\x17.kraalzibar.v1.ZedTokenH\x00R\x0eatLeastAsFresh\x12E\n" +
	"\x11at_exact_snapshot\x18\x04 \x01(\v2\x17.kraalzibar.v1.ZedTokenH\x00R\x0fatExactSnapshotB\r\n" +
	"\vrequirement\"\x94\x02\n" +
	"\x12RelationshipFilter\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tH\x00R\n" +
	"objectType\x88\x01\x01\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tH\x01R\bobjectId\x88\x01\x01\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tH\x02R\brelation\x88\x01\x01\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tH\x03R\vsubjectType\x88\x01\x01\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tH\x04R\tsubjectId\x88\x01\x01B\x0e\n" +
	"\f_object_typeB\f\n" +
	"\n" +
	"_object_idB\v\n" +
	"\t_relationB\x0f\n" +
	"\r_subject_typeB\r\n" +
	"\v_subject_id\"\xba\x04\n" +
	"\x17PermissionExpansionTree\x12E\n" +
	"\x04leaf\x18\x01 \x01(\v2/.kraalzibar.v1.PermissionExpansionTree.LeafNodeH\x00R\x04leaf\x12]\n" +
	"\fintermediate\x18\x02 \x01(\v27.kraalzibar.v1.PermissionExpansionTree.IntermediateNodeH\x00R\fintermediate\x1aE\n" +
	"\bLeafNode\x129\n" +
	"\asubject\x18\x01 \x01(\v2\x1f.kraalzibar.v1.SubjectReferenceR\asubject\x1a\xa9\x02\n" +
	"\x10IntermediateNode\x12_\n" +
	"\toperation\x18\x01 \x01(\x0e2A.kraalzibar.v1.PermissionExpansionTree.IntermediateNode.OperationR\toperation\x12B\n" +
	"\bchildren\x18\x02 \x03(\v2&.kraalzibar.v1.PermissionExpansionTreeR\bchildren\"p\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_UNION\x10\x01\x12\x1a\n" +
	"\x16OPERATION_INTERSECTION\x10\x02\x12\x17\n" +
	"\x13OPERATION_EXCLUSION\x10\x03B\x06\n" +
	"\x04nodeb\x06proto3"

var (
	file_kraalzibar_v1_core_proto_rawDescOnce sync.Once
	file_kraalzibar_v1_core_proto_rawDescData []byte
)

func file_kraalzibar_v1_core_proto_rawDescGZIP() []byte {
	file_kraalzibar_v1_core_proto_rawDescOnce.Do(func() {
		file_kraalzibar_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_core_proto_rawDesc), len(file_kraalzibar_v1_core_proto_rawDesc)))
	})
	return file_kraalzibar_v1_core_proto_rawDescData
}

var file_kraalzibar_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kraalzibar_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kraalzibar_v1_core_proto_goTypes = []any{
	(RelationshipUpdate_Operation)(0),                       // 0: kraalzibar.v1.RelationshipUpdate.Operation
	(PermissionExpansionTree_IntermediateNode_Operation)(0), // 1: kraalzibar.v1.PermissionExpansionTree.IntermediateNode.Operation
	(*ObjectReference)(nil),                                 // 2: kraalzibar.v1.ObjectReference
	(*SubjectReference)(nil),                                // 3: kraalzibar.v1.SubjectReference
	(*Relationship)(nil),                                    // 4: kraalzibar.v1.Relationship
	(*RelationshipUpdate)(nil),                              // 5: kraalzibar.v1.RelationshipUpdate
	(*ZedToken)(nil),                                        // 6: kraalzibar.v1.ZedToken
	(*Consistency)(nil),                                     // 7: kraalzibar.v1.Consistency
	(*RelationshipFilter)(nil),                              // 8: kraalzibar.v1.RelationshipFilter
	(*PermissionExpansionTree)(nil),                         // 9: kraalzibar.v1.PermissionExpansionTree
	(*PermissionExpansionTree_LeafNode)(nil),                // 10: kraalzibar.v1.PermissionExpansionTree.LeafNode
	(*PermissionExpansionTree_IntermediateNode)(nil),        // 11: kraalzibar.v1.PermissionExpansionTree.IntermediateNode
}
var file_kraalzibar_v1_core_proto_depIdxs = []int32{
	2,  // 0: kraalzibar.v1.Relationship.object:type_name -> kraalzibar.v1.ObjectReference
	3,  // 1: kraalzibar.v1.Relationship.subject:type_name -> kraalzibar.v1.SubjectReference
	0,  // 2: kraalzibar.v1.RelationshipUpdate.operation:type_name -> kraalzibar.v1.RelationshipUpdate.Operation
	4,  // 3: kraalzibar.v1.RelationshipUpdate.relationship:type_name -> kraalzibar.v1.Relationship
	6,  // 4: kraalzibar.v1.Consistency.at_least_as_fresh:type_name -> kraalzibar.v1.ZedToken
	6,  // 5: kraalzibar.v1.Consistency.at_exact_snapshot:type_name -> kraalzibar.v1.ZedToken
	10, // 6: kraalzibar.v1.PermissionExpansionTree.leaf:type_name -> kraalzibar.v1.PermissionExpansionTree.LeafNode
	11, // 7: kraalzibar.v1.PermissionExpansionTree.intermediate:type_name -> kraalzibar.v1.PermissionExpansionTree.IntermediateNode
	3,  // 8: kraalzibar.v1.PermissionExpansionTree.LeafNode.subject:type_name -> kraalzibar.v1.SubjectReference
	1,  // 9: kraalzibar.v1.PermissionExpansionTree.IntermediateNode.operation:type_name -> kraalzibar.v1.PermissionExpansionTree.IntermediateNode.Operation
	9,  // 10: kraalzibar.v1.PermissionExpansionTree.IntermediateNode.children:type_name -> kraalzibar.v1.PermissionExpansionTree
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kraalzibar_v1_core_proto_init() }
func file_kraalzibar_v1_core_proto_init() {
	if File_kraalzibar_v1_core_proto != nil {
		return
	}
	file_kraalzibar_v1_core_proto_msgTypes[1].OneofWrappers = []any{}
	file_kraalzibar_v1_core_proto_msgTypes[5].OneofWrappers = []any{
		(*Consistency_FullConsistency)(nil),
		(*Consistency_MinimizeLatency)(nil),
		(*Consistency_AtLeastAsFresh)(nil),
		(*Consistency_AtExactSnapshot)(nil),
	}
	file_kraalzibar_v1_core_proto_msgTypes[6].OneofWrappers = []any{}
	file_kraalzibar_v1_core_proto_msgTypes[7].OneofWrappers = []any{
		(*PermissionExpansionTree_Leaf)(nil),
		(*PermissionExpansionTree_Intermediate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_core_proto_rawDesc), len(file_kraalzibar_v1_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kraalzibar_v1_core_proto_goTypes,
		DependencyIndexes: file_kraalzibar_v1_core_proto_depIdxs,
		EnumInfos:         file_kraalzibar_v1_core_proto_enumTypes,
		MessageInfos:      file_kraalzibar_v1_core_proto_msgTypes,
	}.Build()
	File_kraalzibar_v1_core_proto = out.File
	file_kraalzibar_v1_core_proto_goTypes = nil
	file_kraalzibar_v1_core_proto_depIdxs = nil
}
