// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kraalzibar/v1/permission.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPermissionResponse_Permissionship int32

const (
	CheckPermissionResponse_PERMISSIONSHIP_UNSPECIFIED    CheckPermissionResponse_Permissionship = 0
	CheckPermissionResponse_PERMISSIONSHIP_NO_PERMISSION  CheckPermissionResponse_Permissionship = 1
	CheckPermissionResponse_PERMISSIONSHIP_HAS_PERMISSION CheckPermissionResponse_Permissionship = 2
)

// Enum value maps for CheckPermissionResponse_Permissionship.
var (
	CheckPermissionResponse_Permissionship_name = map[int32]string{
		0: "PERMISSIONSHIP_UNSPECIFIED",
		1: "PERMISSIONSHIP_NO_PERMISSION",
		2: "PERMISSIONSHIP_HAS_PERMISSION",
	}
	CheckPermissionResponse_Permissionship_value = map[string]int32{
		"PERMISSIONSHIP_UNSPECIFIED":    0,
		"PERMISSIONSHIP_NO_PERMISSION":  1,
		"PERMISSIONSHIP_HAS_PERMISSION": 2,
	}
)

func (x CheckPermissionResponse_Permissionship) Enum() *CheckPermissionResponse_Permissionship {
	p := new(CheckPermissionResponse_Permissionship)
	*p = x
	return p
}

func (x CheckPermissionResponse_Permissionship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckPermissionResponse_Permissionship) Descriptor() protoreflect.EnumDescriptor {
	return file_kraalzibar_v1_permission_proto_enumTypes[0].Descriptor()
}

func (CheckPermissionResponse_Permissionship) Type() protoreflect.EnumType {
	return &file_kraalzibar_v1_permission_proto_enumTypes[0]
}

func (x CheckPermissionResponse_Permissionship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckPermissionResponse_Permissionship.Descriptor instead.
func (CheckPermissionResponse_Permissionship) EnumDescriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{1, 0}
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   *Consistency           `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Resource      *ObjectReference       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *CheckPermissionRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *CheckPermissionRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckPermissionResponse struct {
	state          protoimpl.MessageState                 `protogen:"open.v1"`
	CheckedAt      *ZedToken                              `protobuf:"bytes,1,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Permissionship CheckPermissionResponse_Permissionship `protobuf:"varint,2,opt,name=permissionship,proto3,enum=kraalzibar.v1.CheckPermissionResponse_Permissionship" json:"permissionship,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetCheckedAt() *ZedToken {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *CheckPermissionResponse) GetPermissionship() CheckPermissionResponse_Permissionship {
	if x != nil {
		return x.Permissionship
	}
	return CheckPermissionResponse_PERMISSIONSHIP_UNSPECIFIED
}

type ExpandPermissionTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   *Consistency           `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Resource      *ObjectReference       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandPermissionTreeRequest) Reset() {
	*x = ExpandPermissionTreeRequest{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandPermissionTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandPermissionTreeRequest) ProtoMessage() {}

func (x *ExpandPermissionTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandPermissionTreeRequest.ProtoReflect.Descriptor instead.
func (*ExpandPermissionTreeRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *ExpandPermissionTreeRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ExpandPermissionTreeRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExpandPermissionTreeRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type ExpandPermissionTreeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ExpandedAt    *ZedToken                `protobuf:"bytes,1,opt,name=expanded_at,json=expandedAt,proto3" json:"expanded_at,omitempty"`
	Tree          *PermissionExpansionTree `protobuf:"bytes,2,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandPermissionTreeResponse) Reset() {
	*x = ExpandPermissionTreeResponse{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandPermissionTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandPermissionTreeResponse) ProtoMessage() {}

func (x *ExpandPermissionTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandPermissionTreeResponse.ProtoReflect.Descriptor instead.
func (*ExpandPermissionTreeResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *ExpandPermissionTreeResponse) GetExpandedAt() *ZedToken {
	if x != nil {
		return x.ExpandedAt
	}
	return nil
}

func (x *ExpandPermissionTreeResponse) GetTree() *PermissionExpansionTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

type LookupResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   *Consistency           `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	OptionalLimit uint32                 `protobuf:"varint,5,opt,name=optional_limit,json=optionalLimit,proto3" json:"optional_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResourcesRequest) Reset() {
	*x = LookupResourcesRequest{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResourcesRequest) ProtoMessage() {}

func (x *LookupResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResourcesRequest.ProtoReflect.Descriptor instead.
func (*LookupResourcesRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *LookupResourcesRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *LookupResourcesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *LookupResourcesRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *LookupResourcesRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *LookupResourcesRequest) GetOptionalLimit() uint32 {
	if x != nil {
		return x.OptionalLimit
	}
	return 0
}

type LookupResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LookedUpAt    *ZedToken              `protobuf:"bytes,1,opt,name=looked_up_at,json=lookedUpAt,proto3" json:"looked_up_at,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResourcesResponse) Reset() {
	*x = LookupResourcesResponse{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResourcesResponse) ProtoMessage() {}

func (x *LookupResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResourcesResponse.ProtoReflect.Descriptor instead.
func (*LookupResourcesResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *LookupResourcesResponse) GetLookedUpAt() *ZedToken {
	if x != nil {
		return x.LookedUpAt
	}
	return nil
}

func (x *LookupResourcesResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type LookupSubjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   *Consistency           `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Resource      *ObjectReference       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupSubjectsRequest) Reset() {
	*x = LookupSubjectsRequest{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupSubjectsRequest) ProtoMessage() {}

func (x *LookupSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupSubjectsRequest.ProtoReflect.Descriptor instead.
func (*LookupSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *LookupSubjectsRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *LookupSubjectsRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LookupSubjectsRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *LookupSubjectsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

type LookupSubjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LookedUpAt    *ZedToken              `protobuf:"bytes,1,opt,name=looked_up_at,json=lookedUpAt,proto3" json:"looked_up_at,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupSubjectsResponse) Reset() {
	*x = LookupSubjectsResponse{}
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupSubjectsResponse) ProtoMessage() {}

func (x *LookupSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupSubjectsResponse.ProtoReflect.Descriptor instead.
func (*LookupSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *LookupSubjectsResponse) GetLookedUpAt() *ZedToken {
	if x != nil {
		return x.LookedUpAt
	}
	return nil
}

func (x *LookupSubjectsResponse) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

var File_kraalzibar_v1_permission_proto protoreflect.FileDescriptor

const file_kraalzibar_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1ekraalzibar/v1/permission.proto\x12\rkraalzibar.v1\x1a\x18kraalzibar/v1/core.proto\"\xed\x01\n" +
	"\x16CheckPermissionRequest\x12<\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1a.kraalzibar.v1.ConsistencyR\vconsistency\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x1e.kraalzibar.v1.ObjectReferenceR\bresource\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x129\n" +
	"\asubject\x18\x04 \x01(\v2\x1f.kraalzibar.v1.SubjectReferenceR\asubject\"\xa7\x02\n" +
	"\x17CheckPermissionResponse\x126\n" +
	"\n" +
	"checked_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\tcheckedAt\x12]\n" +
	"\x0epermissionship\x18\x02 \x01(\x0e25.kraalzibar.v1.CheckPermissionResponse.PermissionshipR\x0epermissionship\"u\n" +
	"\x0ePermissionship\x12\x1e\n" +
	"\x1aPERMISSIONSHIP_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPERMISSIONSHIP_NO_PERMISSION\x10\x01\x12!\n" +
	"\x1dPERMISSIONSHIP_HAS_PERMISSION\x10\x02\"\xb7\x01\n" +
	"\x1bExpandPermissionTreeRequest\x12<\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1a.kraalzibar.v1.ConsistencyR\vconsistency\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x1e.kraalzibar.v1.ObjectReferenceR\bresource\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"\x94\x01\n" +
	"\x1cExpandPermissionTreeResponse\x128\n" +
	"\vexpanded_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\n" +
	"expandedAt\x12:\n" +
	"\x04tree\x18\x02 \x01(\v2&.kraalzibar.v1.PermissionExpansionTreeR\x04tree\"\xfd\x01\n" +
	"\x16LookupResourcesRequest\x12<\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1a.kraalzibar.v1.ConsistencyR\vconsistency\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x129\n" +
	"\asubject\x18\x04 \x01(\v2\x1f.kraalzibar.v1.SubjectReferenceR\asubject\x12%\n" +
	"\x0eoptional_limit\x18\x05 \x01(\rR\roptionalLimit\"u\n" +
	"\x17LookupResourcesResponse\x129\n" +
	"\flooked_up_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\n" +
	"lookedUpAt\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"\xd4\x01\n" +
	"\x15LookupSubjectsRequest\x12<\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1a.kraalzibar.v1.ConsistencyR\vconsistency\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x1e.kraalzibar.v1.ObjectReferenceR\bresource\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\"\x8e\x01\n" +
	"\x16LookupSubjectsResponse\x129\n" +
	"\flooked_up_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\n" +
	"lookedUpAt\x129\n" +
	"\asubject\x18\x02 \x01(\v2\x1f.kraalzibar.v1.SubjectReferenceR\asubject2\xab\x03\n" +
	"\x11PermissionService\x12`\n" +
	"\x0fCheckPermission\x12%.kraalzibar.v1.CheckPermissionRequest\x1a&.kraalzibar.v1.CheckPermissionResponse\x12o\n" +
	"\x14ExpandPermissionTree\x12*.kraalzibar.v1.ExpandPermissionTreeRequest\x1a+.kraalzibar.v1.ExpandPermissionTreeResponse\x12b\n" +
	"\x0fLookupResources\x12%.kraalzibar.v1.LookupResourcesRequest\x1a&.kraalzibar.v1.LookupResourcesResponse0\x01\x12_\n" +
	"\x0eLookupSubjects\x12$.kraalzibar.v1.LookupSubjectsRequest\x1a%.kraalzibar.v1.LookupSubjectsResponse0\x01b\x06proto3"

var (
	file_kraalzibar_v1_permission_proto_rawDescOnce sync.Once
	file_kraalzibar_v1_permission_proto_rawDescData []byte
)

func file_kraalzibar_v1_permission_proto_rawDescGZIP() []byte {
	file_kraalzibar_v1_permission_proto_rawDescOnce.Do(func() {
		file_kraalzibar_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_permission_proto_rawDesc), len(file_kraalzibar_v1_permission_proto_rawDesc)))
	})
	return file_kraalzibar_v1_permission_proto_rawDescData
}

var file_kraalzibar_v1_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kraalzibar_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kraalzibar_v1_permission_proto_goTypes = []any{
	(CheckPermissionResponse_Permissionship)(0), // 0: kraalzibar.v1.CheckPermissionResponse.Permissionship
	(*CheckPermissionRequest)(nil),              // 1: kraalzibar.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),             // 2: kraalzibar.v1.CheckPermissionResponse
	(*ExpandPermissionTreeRequest)(nil),         // 3: kraalzibar.v1.ExpandPermissionTreeRequest
	(*ExpandPermissionTreeResponse)(nil),        // 4: kraalzibar.v1.ExpandPermissionTreeResponse
	(*LookupResourcesRequest)(nil),              // 5: kraalzibar.v1.LookupResourcesRequest
	(*LookupResourcesResponse)(nil),             // 6: kraalzibar.v1.LookupResourcesResponse
	(*LookupSubjectsRequest)(nil),               // 7: kraalzibar.v1.LookupSubjectsRequest
	(*LookupSubjectsResponse)(nil),              // 8: kraalzibar.v1.LookupSubjectsResponse
	(*Consistency)(nil),                         // 9: kraalzibar.v1.Consistency
	(*ObjectReference)(nil),                     // 10: kraalzibar.v1.ObjectReference
	(*SubjectReference)(nil),                    // 11: kraalzibar.v1.SubjectReference
	(*ZedToken)(nil),                            // 12: kraalzibar.v1.ZedToken
	(*PermissionExpansionTree)(nil),             // 13: kraalzibar.v1.PermissionExpansionTree
}
var file_kraalzibar_v1_permission_proto_depIdxs = []int32{
	9,  // 0: kraalzibar.v1.CheckPermissionRequest.consistency:type_name -> kraalzibar.v1.Consistency
	10, // 1: kraalzibar.v1.CheckPermissionRequest.resource:type_name -> kraalzibar.v1.ObjectReference
	11, // 2: kraalzibar.v1.CheckPermissionRequest.subject:type_name -> kraalzibar.v1.SubjectReference
	12, // 3: kraalzibar.v1.CheckPermissionResponse.checked_at:type_name -> kraalzibar.v1.ZedToken
	0,  // 4: kraalzibar.v1.CheckPermissionResponse.permissionship:type_name -> kraalzibar.v1.CheckPermissionResponse.Permissionship
	9,  // 5: kraalzibar.v1.ExpandPermissionTreeRequest.consistency:type_name -> kraalzibar.v1.Consistency
	10, // 6: kraalzibar.v1.ExpandPermissionTreeRequest.resource:type_name -> kraalzibar.v1.ObjectReference
	12, // 7: kraalzibar.v1.ExpandPermissionTreeResponse.expanded_at:type_name -> kraalzibar.v1.ZedToken
	13, // 8: kraalzibar.v1.ExpandPermissionTreeResponse.tree:type_name -> kraalzibar.v1.PermissionExpansionTree
	9,  // 9: kraalzibar.v1.LookupResourcesRequest.consistency:type_name -> kraalzibar.v1.Consistency
	11, // 10: kraalzibar.v1.LookupResourcesRequest.subject:type_name -> kraalzibar.v1.SubjectReference
	12, // 11: kraalzibar.v1.LookupResourcesResponse.looked_up_at:type_name -> kraalzibar.v1.ZedToken
	9,  // 12: kraalzibar.v1.LookupSubjectsRequest.consistency:type_name -> kraalzibar.v1.Consistency
	10, // 13: kraalzibar.v1.LookupSubjectsRequest.resource:type_name -> kraalzibar.v1.ObjectReference
	12, // 14: kraalzibar.v1.LookupSubjectsResponse.looked_up_at:type_name -> kraalzibar.v1.ZedToken
	11, // 15: kraalzibar.v1.LookupSubjectsResponse.subject:type_name -> kraalzibar.v1.SubjectReference
	1,  // 16: kraalzibar.v1.PermissionService.CheckPermission:input_type -> kraalzibar.v1.CheckPermissionRequest
	3,  // 17: kraalzibar.v1.PermissionService.ExpandPermissionTree:input_type -> kraalzibar.v1.ExpandPermissionTreeRequest
	5,  // 18: kraalzibar.v1.PermissionService.LookupResources:input_type -> kraalzibar.v1.LookupResourcesRequest
	7,  // 19: kraalzibar.v1.PermissionService.LookupSubjects:input_type -> kraalzibar.v1.LookupSubjectsRequest
	2,  // 20: kraalzibar.v1.PermissionService.CheckPermission:output_type -> kraalzibar.v1.CheckPermissionResponse
	4,  // 21: kraalzibar.v1.PermissionService.ExpandPermissionTree:output_type -> kraalzibar.v1.ExpandPermissionTreeResponse
	6,  // 22: kraalzibar.v1.PermissionService.LookupResources:output_type -> kraalzibar.v1.LookupResourcesResponse
	8,  // 23: kraalzibar.v1.PermissionService.LookupSubjects:output_type -> kraalzibar.v1.LookupSubjectsResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_kraalzibar_v1_permission_proto_init() }
func file_kraalzibar_v1_permission_proto_init() {
	if File_kraalzibar_v1_permission_proto != nil {
		return
	}
	file_kraalzibar_v1_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_permission_proto_rawDesc), len(file_kraalzibar_v1_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraalzibar_v1_permission_proto_goTypes,
		DependencyIndexes: file_kraalzibar_v1_permission_proto_depIdxs,
		EnumInfos:         file_kraalzibar_v1_permission_proto_enumTypes,
		MessageInfos:      file_kraalzibar_v1_permission_proto_msgTypes,
	}.Build()
	File_kraalzibar_v1_permission_proto = out.File
	file_kraalzibar_v1_permission_proto_goTypes = nil
	file_kraalzibar_v1_permission_proto_depIdxs = nil
}
