// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kraalzibar/v1/relationship.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*RelationshipUpdate  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRelationshipsRequest) Reset() {
	*x = WriteRelationshipsRequest{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipsRequest) ProtoMessage() {}

func (x *WriteRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*WriteRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRelationshipsRequest) GetUpdates() []*RelationshipUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type WriteRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrittenAt     *ZedToken              `protobuf:"bytes,1,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRelationshipsResponse) Reset() {
	*x = WriteRelationshipsResponse{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipsResponse) ProtoMessage() {}

func (x *WriteRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*WriteRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRelationshipsResponse) GetWrittenAt() *ZedToken {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

type ReadRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   *Consistency           `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Filter        *RelationshipFilter    `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	OptionalLimit uint32                 `protobuf:"varint,3,opt,name=optional_limit,json=optionalLimit,proto3" json:"optional_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRelationshipsRequest) Reset() {
	*x = ReadRelationshipsRequest{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRelationshipsRequest) ProtoMessage() {}

func (x *ReadRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*ReadRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRelationshipsRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ReadRelationshipsRequest) GetFilter() *RelationshipFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadRelationshipsRequest) GetOptionalLimit() uint32 {
	if x != nil {
		return x.OptionalLimit
	}
	return 0
}

type ReadRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadAt        *ZedToken              `protobuf:"bytes,1,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	Relationships []*Relationship        `protobuf:"bytes,2,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRelationshipsResponse) Reset() {
	*x = ReadRelationshipsResponse{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRelationshipsResponse) ProtoMessage() {}

func (x *ReadRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*ReadRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRelationshipsResponse) GetReadAt() *ZedToken {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *ReadRelationshipsResponse) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectTypes   []string               `protobuf:"bytes,1,rep,name=object_types,json=objectTypes,proto3" json:"object_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetObjectTypes() []string {
	if x != nil {
		return x.ObjectTypes
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*RelationshipUpdate  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	ChangedAt     *ZedToken              `protobuf:"bytes,2,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_relationship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_relationship_proto_rawDescGZIP(), []int{5}
}

func (x *WatchResponse) GetUpdates() []*RelationshipUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *WatchResponse) GetChangedAt() *ZedToken {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

var File_kraalzibar_v1_relationship_proto protoreflect.FileDescriptor

const file_kraalzibar_v1_relationship_proto_rawDesc = "" +
	"\n" +
	" kraalzibar/v1/relationship.proto\x12\rkraalzibar.v1\x1a\x18kraalzibar/v1/core.proto\"X\n" +
	"\x19WriteRelationshipsRequest\x12;\n" +
	"\aupdates\x18\x01 \x03(\v2!.kraalzibar.v1.RelationshipUpdateR\aupdates\"T\n" +
	"\x1aWriteRelationshipsResponse\x126\n" +
	"\n" +
	"written_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\twrittenAt\"\xba\x01\n" +
	"\x18ReadRelationshipsRequest\x12<\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1a.kraalzibar.v1.ConsistencyR\vconsistency\x129\n" +
	"\x06filter\x18\x02 \x01(\v2!.kraalzibar.v1.RelationshipFilterR\x06filter\x12%\n" +
	"\x0eoptional_limit\x18\x03 \x01(\rR\roptionalLimit\"\x90\x01\n" +
	"\x19ReadRelationshipsResponse\x120\n" +
	"\aread_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\x06readAt\x12A\n" +
	"\rrelationships\x18\x02 \x03(\v2\x1b.kraalzibar.v1.RelationshipR\rrelationships\"1\n" +
	"\fWatchRequest\x12!\n" +
	"\fobject_types\x18\x01 \x03(\tR\vobjectTypes\"\x84\x01\n" +
	"\rWatchResponse\x12;\n" +
	"\aupdates\x18\x01 \x03(\v2!.kraalzibar.v1.RelationshipUpdateR\aupdates\x126\n" +
	"\n" +
	"changed_at\x18\x02 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\tchangedAt2\xae\x02\n" +
	"\x13RelationshipService\x12i\n" +
	"\x12WriteRelationships\x12(.kraalzibar.v1.WriteRelationshipsRequest\x1a).kraalzibar.v1.WriteRelationshipsResponse\x12f\n" +
	"\x11ReadRelationships\x12'.kraalzibar.v1.ReadRelationshipsRequest\x1a(.kraalzibar.v1.ReadRelationshipsResponse\x12D\n" +
	"\x05Watch\x12\x1b.kraalzibar.v1.WatchRequest\x1a\x1c.kraalzibar.v1.WatchResponse0\x01b\x06proto3"

var (
	file_kraalzibar_v1_relationship_proto_rawDescOnce sync.Once
	file_kraalzibar_v1_relationship_proto_rawDescData []byte
)

func file_kraalzibar_v1_relationship_proto_rawDescGZIP() []byte {
	file_kraalzibar_v1_relationship_proto_rawDescOnce.Do(func() {
		file_kraalzibar_v1_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_relationship_proto_rawDesc), len(file_kraalzibar_v1_relationship_proto_rawDesc)))
	})
	return file_kraalzibar_v1_relationship_proto_rawDescData
}

var file_kraalzibar_v1_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kraalzibar_v1_relationship_proto_goTypes = []any{
	(*WriteRelationshipsRequest)(nil),  // 0: kraalzibar.v1.WriteRelationshipsRequest
	(*WriteRelationshipsResponse)(nil), // 1: kraalzibar.v1.WriteRelationshipsResponse
	(*ReadRelationshipsRequest)(nil),   // 2: kraalzibar.v1.ReadRelationshipsRequest
	(*ReadRelationshipsResponse)(nil),  // 3: kraalzibar.v1.ReadRelationshipsResponse
	(*WatchRequest)(nil),               // 4: kraalzibar.v1.WatchRequest
	(*WatchResponse)(nil),              // 5: kraalzibar.v1.WatchResponse
	(*RelationshipUpdate)(nil),         // 6: kraalzibar.v1.RelationshipUpdate
	(*ZedToken)(nil),                   // 7: kraalzibar.v1.ZedToken
	(*Consistency)(nil),                // 8: kraalzibar.v1.Consistency
	(*RelationshipFilter)(nil),         // 9: kraalzibar.v1.RelationshipFilter
	(*Relationship)(nil),               // 10: kraalzibar.v1.Relationship
}
var file_kraalzibar_v1_relationship_proto_depIdxs = []int32{
	6,  // 0: kraalzibar.v1.WriteRelationshipsRequest.updates:type_name -> kraalzibar.v1.RelationshipUpdate
	7,  // 1: kraalzibar.v1.WriteRelationshipsResponse.written_at:type_name -> kraalzibar.v1.ZedToken
	8,  // 2: kraalzibar.v1.ReadRelationshipsRequest.consistency:type_name -> kraalzibar.v1.Consistency
	9,  // 3: kraalzibar.v1.ReadRelationshipsRequest.filter:type_name -> kraalzibar.v1.RelationshipFilter
	7,  // 4: kraalzibar.v1.ReadRelationshipsResponse.read_at:type_name -> kraalzibar.v1.ZedToken
	10, // 5: kraalzibar.v1.ReadRelationshipsResponse.relationships:type_name -> kraalzibar.v1.Relationship
	6,  // 6: kraalzibar.v1.WatchResponse.updates:type_name -> kraalzibar.v1.RelationshipUpdate
	7,  // 7: kraalzibar.v1.WatchResponse.changed_at:type_name -> kraalzibar.v1.ZedToken
	0,  // 8: kraalzibar.v1.RelationshipService.WriteRelationships:input_type -> kraalzibar.v1.WriteRelationshipsRequest
	2,  // 9: kraalzibar.v1.RelationshipService.ReadRelationships:input_type -> kraalzibar.v1.ReadRelationshipsRequest
	4,  // 10: kraalzibar.v1.RelationshipService.Watch:input_type -> kraalzibar.v1.WatchRequest
	1,  // 11: kraalzibar.v1.RelationshipService.WriteRelationships:output_type -> kraalzibar.v1.WriteRelationshipsResponse
	3,  // 12: kraalzibar.v1.RelationshipService.ReadRelationships:output_type -> kraalzibar.v1.ReadRelationshipsResponse
	5,  // 13: kraalzibar.v1.RelationshipService.Watch:output_type -> kraalzibar.v1.WatchResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kraalzibar_v1_relationship_proto_init() }
func file_kraalzibar_v1_relationship_proto_init() {
	if File_kraalzibar_v1_relationship_proto != nil {
		return
	}
	file_kraalzibar_v1_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_relationship_proto_rawDesc), len(file_kraalzibar_v1_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraalzibar_v1_relationship_proto_goTypes,
		DependencyIndexes: file_kraalzibar_v1_relationship_proto_depIdxs,
		MessageInfos:      file_kraalzibar_v1_relationship_proto_msgTypes,
	}.Build()
	File_kraalzibar_v1_relationship_proto = out.File
	file_kraalzibar_v1_relationship_proto_goTypes = nil
	file_kraalzibar_v1_relationship_proto_depIdxs = nil
}
