// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kraalzibar/v1/schema.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSchemaRequest) Reset() {
	*x = WriteSchemaRequest{}
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSchemaRequest) ProtoMessage() {}

func (x *WriteSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSchemaRequest.ProtoReflect.Descriptor instead.
func (*WriteSchemaRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *WriteSchemaRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *WriteSchemaRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type WriteSchemaResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	WrittenAt                 *ZedToken              `protobuf:"bytes,1,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	BreakingChangesOverridden bool                   `protobuf:"varint,2,opt,name=breaking_changes_overridden,json=breakingChangesOverridden,proto3" json:"breaking_changes_overridden,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WriteSchemaResponse) Reset() {
	*x = WriteSchemaResponse{}
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSchemaResponse) ProtoMessage() {}

func (x *WriteSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSchemaResponse.ProtoReflect.Descriptor instead.
func (*WriteSchemaResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *WriteSchemaResponse) GetWrittenAt() *ZedToken {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

func (x *WriteSchemaResponse) GetBreakingChangesOverridden() bool {
	if x != nil {
		return x.BreakingChangesOverridden
	}
	return false
}

type ReadSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSchemaRequest) Reset() {
	*x = ReadSchemaRequest{}
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSchemaRequest) ProtoMessage() {}

func (x *ReadSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSchemaRequest.ProtoReflect.Descriptor instead.
func (*ReadSchemaRequest) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_schema_proto_rawDescGZIP(), []int{2}
}

type ReadSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSchemaResponse) Reset() {
	*x = ReadSchemaResponse{}
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSchemaResponse) ProtoMessage() {}

func (x *ReadSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraalzibar_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSchemaResponse.ProtoReflect.Descriptor instead.
func (*ReadSchemaResponse) Descriptor() ([]byte, []int) {
	return file_kraalzibar_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *ReadSchemaResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

var File_kraalzibar_v1_schema_proto protoreflect.FileDescriptor

const file_kraalzibar_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x1akraalzibar/v1/schema.proto\x12\rkraalzibar.v1\x1a\x18kraalzibar/v1/core.proto\"B\n" +
	"\x12WriteSchemaRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x8d\x01\n" +
	"\x13WriteSchemaResponse\x126\n" +
	"\n" +
	"written_at\x18\x01 \x01(\v2\x17.kraalzibar.v1.ZedTokenR\twrittenAt\x12>\n" +
	"\x1bbreaking_changes_overridden\x18\x02 \x01(\bR\x19breakingChangesOverridden\"\x13\n" +
	"\x11ReadSchemaRequest\",\n" +
	"\x12ReadSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema2\xb8\x01\n" +
	"\rSchemaService\x12T\n" +
	"\vWriteSchema\x12!.kraalzibar.v1.WriteSchemaRequest\x1a\".kraalzibar.v1.WriteSchemaResponse\x12Q\n" +
	"\n" +
	"ReadSchema\x12 .kraalzibar.v1.ReadSchemaRequest\x1a!.kraalzibar.v1.ReadSchemaResponseb\x06proto3"

var (
	file_kraalzibar_v1_schema_proto_rawDescOnce sync.Once
	file_kraalzibar_v1_schema_proto_rawDescData []byte
)

func file_kraalzibar_v1_schema_proto_rawDescGZIP() []byte {
	file_kraalzibar_v1_schema_proto_rawDescOnce.Do(func() {
		file_kraalzibar_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_schema_proto_rawDesc), len(file_kraalzibar_v1_schema_proto_rawDesc)))
	})
	return file_kraalzibar_v1_schema_proto_rawDescData
}

var file_kraalzibar_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kraalzibar_v1_schema_proto_goTypes = []any{
	(*WriteSchemaRequest)(nil),  // 0: kraalzibar.v1.WriteSchemaRequest
	(*WriteSchemaResponse)(nil), // 1: kraalzibar.v1.WriteSchemaResponse
	(*ReadSchemaRequest)(nil),   // 2: kraalzibar.v1.ReadSchemaRequest
	(*ReadSchemaResponse)(nil),  // 3: kraalzibar.v1.ReadSchemaResponse
	(*ZedToken)(nil),            // 4: kraalzibar.v1.ZedToken
}
var file_kraalzibar_v1_schema_proto_depIdxs = []int32{
	4, // 0: kraalzibar.v1.WriteSchemaResponse.written_at:type_name -> kraalzibar.v1.ZedToken
	0, // 1: kraalzibar.v1.SchemaService.WriteSchema:input_type -> kraalzibar.v1.WriteSchemaRequest
	2, // 2: kraalzibar.v1.SchemaService.ReadSchema:input_type -> kraalzibar.v1.ReadSchemaRequest
	1, // 3: kraalzibar.v1.SchemaService.WriteSchema:output_type -> kraalzibar.v1.WriteSchemaResponse
	3, // 4: kraalzibar.v1.SchemaService.ReadSchema:output_type -> kraalzibar.v1.ReadSchemaResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kraalzibar_v1_schema_proto_init() }
func file_kraalzibar_v1_schema_proto_init() {
	if File_kraalzibar_v1_schema_proto != nil {
		return
	}
	file_kraalzibar_v1_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraalzibar_v1_schema_proto_rawDesc), len(file_kraalzibar_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraalzibar_v1_schema_proto_goTypes,
		DependencyIndexes: file_kraalzibar_v1_schema_proto_depIdxs,
		MessageInfos:      file_kraalzibar_v1_schema_proto_msgTypes,
	}.Build()
	File_kraalzibar_v1_schema_proto = out.File
	file_kraalzibar_v1_schema_proto_goTypes = nil
	file_kraalzibar_v1_schema_proto_depIdxs = nil
}
